stages:
  - build-and-test

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - make
    - ls -1sh ~/artifacts/xenial64/ || true
    - ls -1sh ~/artifacts/bionic64/ || true
